# Generated by Django 3.1.7 on 2021-06-30 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifehack', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lifehack',
            new_name='Test',
        ),
    ]
