# Generated by Django 3.2.5 on 2021-07-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifehack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='role',
        ),
    ]
