# Generated by Django 3.2.5 on 2021-07-23 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifehack', '0002_auto_20210723_2124'),
        ('lifehack', '0002_rename_type_user_role'),
    ]

    operations = [
    ]
