# Generated by Django 3.1.7 on 2021-07-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifehack', '0002_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
