# Generated by Django 3.2.5 on 2021-07-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifehack', '0003_chat_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='attachments',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
