# Generated by Django 3.1.7 on 2021-07-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifehack', '0003_auto_20210723_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='attachments',
            field=models.ImageField(blank=True, null=True, upload_to='attachments'),
        ),
        migrations.AlterField(
            model_name='app',
            name='comments',
            field=models.CharField(blank=True, default=None, max_length=1000),
        ),
    ]
