# Generated by Django 3.1.7 on 2021-07-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifehack', '0004_auto_20210720_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='attachments',
            field=models.CharField(blank=True, max_length=90000, null=True),
        ),
    ]
