# Generated by Django 3.1.7 on 2021-07-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifehack', '0004_auto_20210723_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='comments',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
