# Generated by Django 3.1.7 on 2021-07-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifehack', '0005_auto_20210720_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='attachments',
            field=models.CharField(blank=True, max_length=1000000000, null=True),
        ),
    ]
