# Generated by Django 3.1.7 on 2021-07-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifehack', '0006_auto_20210720_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='attachments',
            field=models.ImageField(blank=True, null=True, upload_to='attachments'),
        ),
    ]
