# Generated by Django 3.2.5 on 2021-07-20 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifehack', '0004_alter_chat_attachments'),
        ('lifehack', '0006_auto_20210720_1433'),
    ]

    operations = [
    ]
