# Generated by Django 3.2.5 on 2021-07-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifehack', '0007_merge_20210720_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='attachments',
            field=models.CharField(blank=True, max_length=1000000000, null=True),
        ),
    ]
