# Generated by Django 3.1.7 on 2021-07-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifehack', '0008_auto_20210721_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='attachments',
            field=models.ImageField(blank=True, null=True, upload_to='attachments'),
        ),
    ]
