import moment from 'moment';

function getRandomInt(max) {
    return Math.floor(Math.random() * max);
}

export const subjectObject = [
    {subj: 'English', key: 1},
    {subj: 'Chinese', key: 2},
    {subj: 'E Math', key: 3},
    {subj: 'A Math', key: 4},
    {subj: 'Physics', key: 5},
    {subj: 'Chemistry', key: 6},
    {subj: 'Biology', key: 7},
    {subj: 'History', key: 8},
    {subj: 'Literature', key: 9},
  ]

export const subjectList = subjectObject.map((item)=>{return item.subj})

export const pastQuestions = [
    {name: 'Donovan',message: 'What is going on??',class:'Math',timestamp: moment()},
    {name: 'Donovan',message: 'Redox equations?',class:'Chemistry',timestamp: moment()},
    {name: 'Donovan',message: 'Who is Hitler?',class:'History',timestamp: moment()},
    {name: 'Donovan',message: 'Is yellow actually yellow',class:'Art',timestamp: moment()},
    {name: 'Donovan',message: '2+2+3??',class:'Math',timestamp: moment()},
    {name: 'Donovan',message: 'Alkane is what',class:'Chemistry',timestamp: moment()},
    {name: 'Donovan',message: 'What happen yesterday',class:'History',timestamp: moment()},
    {name: 'Donovan',message: 'Is blue and purple burpple',class:'Art',timestamp: moment()},
    {name: 'Donovan',message: 'Can I use this irl',class:'Math',timestamp: moment()},
    {name: 'Donovan',message: 'Ionic and Covalent got what difference',class:'Chemistry',timestamp: moment()},
    {name: 'Donovan',message: 'Why hitler never win',class:'History',timestamp: moment()},
    {name: 'Donovan',message: 'Can draw me?',class:'Art',timestamp: moment()},
  ]

export const studentResultsData = [
    {name: 'Amierul Ngan',class:'3E1', gender:'Female', result:'62', grade: 'B4'},
    {name: 'Bishan Meng',class:'3E1', gender:'Male', result:'44', grade: 'E8'},
    {name: 'Cheng Wen Kai ',class:'3E1', gender:'Male', result:'58', grade: 'C5'},
    {name: 'Choong Jia Ling ',class:'3E1', gender:'Female', result:'57', grade: 'C5'},
    {name: 'Hao Rui Lin ',class:'3E1', gender:'Female', result:'40', grade: 'E8'},
    {name: 'Jomo Kwame Meng',class:'3E1', gender:'Female', result:'67', grade: 'B3'},
    {name: 'Koh Ling Hui ',class:'3E1', gender:'Female', result:'51', grade: 'C6'},
    {name: 'Lam Zheng En ',class:'3E1', gender:'Male', result:'70', grade: 'A2'},
    {name: 'Leung Wen Kai ',class:'3E1', gender:'Male', result:'78', grade: 'A1'},
    {name: 'Liew Zhi Hui ',class:'3E1', gender:'Male', result:'83', grade: 'A1'},
    {name: 'Lim Kai Feng ',class:'3E1', gender:'Male', result:'57', grade: 'C5'},
    {name: 'Low Jia Wen ',class:'3E1', gender:'Male', result:'74', grade: 'A2'},
    {name: 'Lu Yan Ling ',class:'3E1', gender:'Female', result:'84', grade: 'A1'},
    {name: 'Lye Jia Sheng ',class:'3E1', gender:'Male', result:'45', grade: 'D7'},
    {name: 'Noorfarzanah Muzammil',class:'3E1', gender:'Female', result:'78', grade: 'A1'},
    {name: 'Oon Yi Xi ',class:'3E1', gender:'Female', result:'61', grade: 'B4'},
    {name: 'Poon Jia De ',class:'3E1', gender:'Female', result:'43', grade: 'E8'},
    {name: 'Pria Zulkhairie',class:'3E1', gender:'Female', result:'120', grade: 'C6'},
    {name: 'Qian Jia Jia ',class:'3E1', gender:'Male', result:'83', grade: 'A1'},
    {name: 'Tatparanandam Idris',class:'3E1', gender:'Male', result:'65', grade: 'B3'},
    {name: 'Teu Ngu Gurusamy',class:'3E1', gender:'Male', result:'49', grade: 'D7'},
    {name: 'To Mei Ratnam',class:'3E1', gender:'Female', result:'54', grade: 'C6'},
    {name: 'Toh Jia Min ',class:'3E1', gender:'Male', result:'64', grade: 'B4'},
    {name: 'Umasundari Salleh',class:'3E1', gender:'Male', result:'46', grade: 'D7'},
    {name: 'Woo Jun Jie ',class:'3E1', gender:'Male', result:'40', grade: 'D7'},
    {name: 'Yang Kok Meng ',class:'3E1', gender:'Male', result:'76', grade: 'A1'},
    {name: 'Yeung Jia De ',class:'3E1', gender:'Female', result:'84', grade: 'A1'},
    {name: 'Zhu Xi Ling ',class:'3E1', gender:'Female', result:'73', grade: 'A2'},
    {name: 'Zhuo Yi Xin ',class:'3E1', gender:'Male', result:'72', grade: 'A2'},
  ]

export const lessonData = [
    // {date: "15-06-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    // {date: "16-06-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    // {date: "17-06-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    // {date: "18-06-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    // {date: "19-06-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    // {date: "20-06-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    // {date: "21-06-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    // {date: "22-06-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    // {date: "23-06-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    // {date: "24-06-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    // {date: "25-06-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    // {date: "26-06-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    // {date: "27-06-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    // {date: "28-06-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    // {date: "29-06-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    // {date: "30-06-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    // {date: "01-07-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    // {date: "02-07-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    // {date: "03-07-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    {date: "04-07-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    {date: "05-07-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    {date: "06-07-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    {date: "07-07-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    {date: "08-07-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    {date: "09-07-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    {date: "10-07-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    {date: "11-07-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    {date: "12-07-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    {date: "13-07-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    {date: "14-07-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    {date: "15-07-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    {date: "16-07-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    {date: "17-07-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    {date: "18-07-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    {date: "19-07-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    {date: "20-07-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    {date: "21-07-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    {date: "22-07-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    {date: "23-07-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
    {date: "24-07-21", subject: subjectList[getRandomInt(9)], topic: `Chapter ${getRandomInt(10)+1}`, score: `${getRandomInt(100)}/100`},
  ];

export const lessonClassData = [
    { item: 'I understand', count: 40, percent: 0.4 },
    { item: 'I am lost', count: 21, percent: 0.21 },
    { item: 'Slow Down', count: 17, percent: 0.17 },
    { item: 'Speed Up', count: 13, percent: 0.13 },
];

export const lessonClassDataTime = [
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: 40+getRandomInt(15), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "I am lost", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: 70+getRandomInt(20), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "I understand", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: 30+getRandomInt(12), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Slow down", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: 90+getRandomInt(10), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: 90+getRandomInt(10), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: 90+getRandomInt(10), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: 90+getRandomInt(10), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: 90+getRandomInt(10), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: 90+getRandomInt(10), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: 90+getRandomInt(10), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: 90+getRandomInt(10), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: 90+getRandomInt(10), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: 90+getRandomInt(10), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: 90+getRandomInt(10), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: 90+getRandomInt(10), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: 90+getRandomInt(10), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: 90+getRandomInt(10), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: 90+getRandomInt(10), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: 90+getRandomInt(10), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: 90+getRandomInt(10), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: 90+getRandomInt(10), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: 90+getRandomInt(10), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: 90+getRandomInt(10), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
    {type: "Speed up", time: getRandomInt(120), student: studentResultsData[getRandomInt(25)].name},
  ]

export  const allStudentOverallSummaryData = {
    "English":[
        {State: "02-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "03-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "04-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "05-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "06-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "07-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "08-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "09-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "10-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "11-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "12-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "13-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "14-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "15-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "16-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "17-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "18-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "19-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "20-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "21-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "22-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "23-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "24-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
    ],
    "Chinese":[
        {State: "02-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "03-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "04-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "05-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "06-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "07-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "08-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "09-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "10-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "11-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "12-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "13-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "14-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "15-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "16-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "17-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "18-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "19-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "20-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "21-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "22-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "23-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "24-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
    ],
    "E Math":[
        {State: "02-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "03-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "04-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "05-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "06-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "07-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "08-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "09-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "10-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "11-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "12-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "13-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "14-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "15-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "16-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "17-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "18-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "19-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "20-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "21-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "22-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "23-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "24-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
    ],
    "A Math":[
        {State: "02-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "03-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "04-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "05-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "06-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "07-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "08-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "09-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "10-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "11-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "12-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "13-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "14-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "15-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "16-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "17-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "18-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "19-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "20-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "21-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "22-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "23-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "24-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
    ],
    "Physics":[
        {State: "02-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "03-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "04-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "05-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "06-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "07-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "08-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "09-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "10-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "11-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "12-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "13-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "14-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "15-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "16-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "17-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "18-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "19-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "20-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "21-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "22-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "23-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "24-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
    ],
    "Chemistry":[
        {State: "02-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "03-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "04-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "05-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "06-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "07-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "08-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "09-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "10-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "11-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "12-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "13-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "14-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "15-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "16-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "17-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "18-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "19-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "20-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "21-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "22-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "23-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "24-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
    ],
    "Biology":[
        {State: "02-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "03-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "04-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "05-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "06-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "07-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "08-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "09-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "10-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "11-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "12-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "13-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "14-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "15-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "16-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "17-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "18-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "19-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "20-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "21-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "22-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "23-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "24-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
    ],
    "History":[
        {State: "02-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "03-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "04-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "05-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "06-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "07-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "08-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "09-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "10-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "11-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "12-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "13-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "14-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "15-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "16-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "17-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "18-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "19-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "20-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "21-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "22-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "23-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "24-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
    ],
    "Literature":[
        {State: "02-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "03-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "04-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "05-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "06-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "07-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "08-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "09-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "10-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "11-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "12-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "13-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "14-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "15-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "16-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "17-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "18-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "19-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "20-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "21-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "22-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "23-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
        {State: "24-07-21","I understand": getRandomInt(10),"I am lost": getRandomInt(10), "Slow Down": getRandomInt(10), "Speed Up": getRandomInt(10)},
    ],
}

export  const studentOverallSummaryData = (subject, data = allStudentOverallSummaryData) => {
    return data[subject]
}

  export const marksObject = studentOverallSummaryData('English')?.map((item)=>{
    return item.State
  })

  export const lessonAlertData = [
    {name: 'Poon Jia De ',class:'3E1', iAmLost: 18, slowDown: 17, grade: 'E8'},
    {name: 'Umasundari Salleh',class:'3E1', iAmLost: 11, slowDown: 19, grade: 'D7'},
    {name: 'Woo Jun Jie ',class:'3E1', iAmLost: 10, slowDown: 18, grade: 'D7'},
    {name: 'Lye Jia Sheng ',class:'3E1', iAmLost: 9, slowDown: 15, grade: 'D7'},
    {name: 'Cheng Wen Kai ',class:'3E1', iAmLost: 11, slowDown: 6, grade: 'C5'},
  ]

  export const dataResults = (item) => {
    const allResults = {
      "English": [
        {exam: "WA1",marks: 40+getRandomInt(40)},
        {exam: "WA2",marks: 40+getRandomInt(40)},
        {exam: "WA3",marks: 40+getRandomInt(40)},
        {exam: "WA4",marks: 40+getRandomInt(40)},
      ],
      "Chinese": [
        {exam: "WA1",marks: 40+getRandomInt(40)},
        {exam: "WA2",marks: 40+getRandomInt(40)},
        {exam: "WA3",marks: 40+getRandomInt(40)},
        {exam: "WA4",marks: 40+getRandomInt(40)},
      ],
      "E Math": [
        {exam: "WA1",marks: 40+getRandomInt(40)},
        {exam: "WA2",marks: 40+getRandomInt(40)},
        {exam: "WA3",marks: 40+getRandomInt(40)},
        {exam: "WA4",marks: 40+getRandomInt(40)},
      ],
      "A Math": [
        {exam: "WA1",marks: 40+getRandomInt(40)},
        {exam: "WA2",marks: 40+getRandomInt(40)},
        {exam: "WA3",marks: 40+getRandomInt(40)},
        {exam: "WA4",marks: 40+getRandomInt(40)},
      ],
      "Physics": [
        {exam: "WA1",marks: 40+getRandomInt(40)},
        {exam: "WA2",marks: 40+getRandomInt(40)},
        {exam: "WA3",marks: 40+getRandomInt(40)},
        {exam: "WA4",marks: 40+getRandomInt(40)},
      ],
      "Chemistry": [
        {exam: "WA1",marks: 40+getRandomInt(40)},
        {exam: "WA2",marks: 40+getRandomInt(40)},
        {exam: "WA3",marks: 40+getRandomInt(40)},
        {exam: "WA4",marks: 40+getRandomInt(40)},
      ],
      "Biology": [
        {exam: "WA1",marks: 40+getRandomInt(40)},
        {exam: "WA2",marks: 40+getRandomInt(40)},
        {exam: "WA3",marks: 40+getRandomInt(40)},
        {exam: "WA4",marks: 40+getRandomInt(40)},
      ],
      "History": [
        {exam: "WA1",marks: 40+getRandomInt(40)},
        {exam: "WA2",marks: 40+getRandomInt(40)},
        {exam: "WA3",marks: 40+getRandomInt(40)},
        {exam: "WA4",marks: 40+getRandomInt(40)},
      ],
      "Literature": [
        {exam: "WA1",marks: 40+getRandomInt(40)},
        {exam: "WA2",marks: 40+getRandomInt(40)},
        {exam: "WA3",marks: 40+getRandomInt(40)},
        {exam: "WA4",marks: 40+getRandomInt(40)},
      ],
    }
    return allResults[item]
  }